### ISSUE TITLE
Issues from Humdata Checklist

### ISSUE THREAD

**Issue by collinschwantes** [ecohealthalliance/One-Health-Database-Africa#5]
HDX quality assurance (QA) officers should check each new or updated dataset against this checklist to ensure datasets shared on HDX meet the minimum HDX quality standards for datasets. The checklist is in three parts: a) a checklist for dataset resources, b) a data responsibility checklist and c) a metadata quality checklist. Each of these checklists are presented below.

A. Data Resource

- [x] Download link works
- [x] Link is not password protected
- [x] File is in a machine readable format
- [x] No PII in the data file
- [x] No DII ( need to confirm what DII means)
- [x] No individual survey data
- [x] stated file type and actual file type are consistent
- [x] if Zipped shaped, file is properly typed

B. Data responsibility
- [x] Data is safe to share and not potentially sensitive

C. Metadata Quality
- [x] Dataset has a title
- [x] title is consistent with contents
- [x] title is not in camel case
- [x] title does not start with a place name
- [x] title does not include a relative time reference (current, latest, new, old, etc)
- [x] dataset has a description
- [x] description reflects contents
- [x] No pii in the description - generic email addresses are okay (data@ecohealthalliance.org)
- [ ] Dataset has sources
- [ ] sources are valid
- [x] Dataset has a date of dataset attribute
- [x] date is not not in the future
- [ ] Dataset date is consistent with the freshness of the data - data are as up to date as suggested by the dataset date
- [x] the dataset has an expected update frequency
- [x] data are fresh in accordance with update frequency
- [x] The dataset has at least one location
- [x] Specified location matches location for the data
- [x] The dataset has a license
- [ ] The dataset has a methodology
- [ ] The caveats and comments text is clear and meaningful
- [x] If the dataset contains subnational data, has it been flagged?
